services:
  tire-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tire-bot
    image: tire-bot
    env_file:
      - .env
    depends_on:
      - tire-bot-postgres
      - tire-bot-redis
    networks:
      - tire-bot-network

  tire-bot-postgres:
    image: postgres:15
    container_name: tire-bot-postgres
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - tire-bot-network

  tire-bot-redis:
    image: redis:latest
    container_name: tire-bot-redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - tire-bot-network

networks:
  tire-bot-network:
    external: true
