"""Update motorcycles column

Revision ID: 1ec4568e942c
Revises: 3ce05fd1f4cc
Create Date: 2025-06-11 12:55:00.769638

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec4568e942c'
down_revision: Union[str, None] = '3ce05fd1f4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('user_telegram_id', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('fk_motorcycles_user_id_users'), 'motorcycles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_motorcycles_user_telegram_id_users'), 'motorcycles', 'users', ['user_telegram_id'], ['telegram_id'])
    op.drop_column('motorcycles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_motorcycles_user_telegram_id_users'), 'motorcycles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_motorcycles_user_id_users'), 'motorcycles', 'users', ['user_id'], ['id'])
    op.drop_column('motorcycles', 'user_telegram_id')
    # ### end Alembic commands ###
