"""Rename model field to motorcycle_model

Revision ID: 298393900804
Revises: 1ec4568e942c
Create Date: 2025-06-13 11:18:17.630825

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298393900804'
down_revision: Union[str, None] = '1ec4568e942c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('motorcycle_model', sa.String(length=50), nullable=False))
    op.drop_column('motorcycles', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('motorcycles', 'motorcycle_model')
    # ### end Alembic commands ###
