"""Add worker to apptication

Revision ID: 5b31c6af2283
Revises: 78799b6157e0
Create Date: 2025-06-29 15:51:56.264899

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b31c6af2283'
down_revision: Union[str, None] = '78799b6157e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('worker_telegram_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'worker_telegram_id')
    # ### end Alembic commands ###
