"""Add location to application

Revision ID: 7294943c9a27
Revises: 5b31c6af2283
Create Date: 2025-06-29 17:25:42.444198

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7294943c9a27'
down_revision: Union[str, None] = '5b31c6af2283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'longitude')
    op.drop_column('applications', 'latitude')
    # ### end Alembic commands ###
