"""Update motorcycles table and user roles

Revision ID: 78799b6157e0
Revises: 6b7f9ae4092c
Create Date: 2025-06-22 14:51:45.701995

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78799b6157e0'
down_revision: Union[str, None] = '6b7f9ae4092c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('motorcycles', 'motorcycle_model',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_column('motorcycles', 'name')
    op.drop_column('motorcycles', 'brand')
    op.drop_column('motorcycles', 'engine')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('engine', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('motorcycles', sa.Column('brand', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('motorcycles', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.alter_column('motorcycles', 'motorcycle_model',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
