"""Add chat_id column in users table

Revision ID: a745e1211665
Revises: 7294943c9a27
Create Date: 2025-07-05 12:26:18.864716

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a745e1211665'
down_revision: Union[str, None] = '7294943c9a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.String(length=128), nullable=True))
    op.create_unique_constraint(op.f('uq_users_chat_id'), 'users', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_chat_id'), 'users', type_='unique')
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###
