"""Add columns admin_comment and photo_result_id in applications table

Revision ID: f3c9f20272e1
Revises: 5b3cde191ef9
Create Date: 2025-08-17 10:47:45.992857

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c9f20272e1'
down_revision: Union[str, None] = '5b3cde191ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('admin_comment', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('photo_result_id', sa.String(), nullable=True))
    op.alter_column('applications', 'number',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'number',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('application_number_seq'::regclass)"),
               existing_nullable=False)
    op.drop_column('applications', 'photo_result_id')
    op.drop_column('applications', 'admin_comment')
    # ### end Alembic commands ###
