"""Add number column to applications table

Revision ID: f765414f1d94
Revises: a745e1211665
Create Date: 2025-07-06 17:11:12.787691

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f765414f1d94'
down_revision: Union[str, None] = 'a745e1211665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('number', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_applications_number'), 'applications', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_number'), table_name='applications')
    op.drop_column('applications', 'number')
    # ### end Alembic commands ###
